export type Selector = {
  name: string
  style: string
}

// TODO (amado): This file is so simple, it can be autogenerated from the css file!!!

// id selectors
export const banner: Selector = { name: "banner", style: "#banner" }
export const footer: Selector = { name: "footer", style: "#footer" }
export const greenCheckmark: Selector = { name: "green-checkmark", style: "#green-checkmark" }
export const logo: Selector = { name: "logo", style: "#logo" }
export const magic: Selector = { name: "magic", style: "#magic" }
export const notFoundError: Selector = { name: "not-found-error", style: "#not-found-error" }
export const notFoundErrorFail: Selector = { name: "not-found-error-fail", style: "#not-found-error-fail" }
export const redX: Selector = { name: "red-x", style: "#red-x" }
export const root: Selector = { name: "root", style: "#root" }

// class selectors
export const absoluteLeft: Selector = { name: "absolute-left", style: ".absolute-left" }
export const absoluteRight: Selector = { name: "absolute-right", style: ".absolute-right" }
export const backwardRotatingGreenCheckmark: Selector = { name: "backward-rotating-green-checkmark", style: ".backward-rotating-green-checkmark" }
export const backwardRotatingRedX: Selector = { name: "backward-rotating-red-x", style: ".backward-rotating-red-x" }
export const curlyBrace: Selector = { name: "curly-brace", style: ".curly-brace" }
export const fixed: Selector = { name: "fixed", style: ".fixed" }
export const flipCardInner: Selector = { name: "flip-card-inner", style: ".flip-card-inner" }
export const forwardRotatingGreenCheckmark: Selector = { name: "forward-rotating-green-checkmark", style: ".forward-rotating-green-checkmark" }
export const forwardRotatingRedX: Selector = { name: "forward-rotating-red-x", style: ".forward-rotating-red-x" }
export const leftBox: Selector = { name: "left-box", style: ".left-box" }
export const leftToRight: Selector = { name: "left-to-right", style: ".left-to-right" }
export const rightBox: Selector = { name: "right-box", style: ".right-box" }
export const rightToLeft: Selector = { name: "right-to-left", style: ".right-to-left" }
export const rotateY0: Selector = { name: "rotateY-0", style: ".rotateY-0" }
export const rotateY180: Selector = { name: "rotateY-180", style: ".rotateY-180" }
export const symbol: Selector = { name: "symbol", style: ".symbol" }
export const version: Selector = { name: "version", style: ".version" }